# Generated by Django 4.0.5 on 2022-07-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookid', models.CharField(db_column='book_id', max_length=80)),
                ('bookimgid', models.CharField(db_column='book_img_id', max_length=10)),
                ('bookname', models.CharField(db_column='book_name', max_length=500)),
                ('bookwritter', models.CharField(db_column='book_writter', max_length=50)),
                ('bookmaker', models.CharField(db_column='book_maker', max_length=50)),
                ('bookdate', models.DateField(auto_now=True, db_column='book_date')),
            ],
            options={
                'db_table': 'booksdata',
            },
        ),
    ]
