# Generated by Django 4.0.5 on 2022-07-04 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_books'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book_data',
        ),
    ]
