# Generated by Django 4.0.5 on 2022-07-06 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_book_data_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book_data',
        ),
    ]
