# Generated by Django 4.0.5 on 2022-07-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_book_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userpick',
            field=models.CharField(db_column='usage_flag', default='', max_length=10),
        ),
    ]
