# Generated by Django 4.0.5 on 2022-07-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_userpick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userpick',
            field=models.TextField(db_column='usage_flag', default=''),
        ),
    ]
