# Generated by Django 4.0.5 on 2022-07-06 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookcrawl', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dashboard',
            table='dashboard',
        ),
    ]
