# Generated by Django 4.0.5 on 2022-07-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcrawl', '0004_alter_dashboard_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='age',
            field=models.IntegerField(),
        ),
    ]
