# Generated by Django 4.0.5 on 2022-07-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcrawl', '0005_dashboard_cost_alter_dashboard_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='cost',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
